### ISSUE TITLE
Missing Digilent Zybo support

### ISSUE THREAD

**Issue by Livius90** [Xilinx/yocto-manifests#5]
Hi!
In Xilinx BSP there are some supported Digilent Zybo boards, however when i want to use these machines in Yocto conf the building process will be failed, because system.xsa file is missing in hdf-examples for zybo-zynq7 and zybo-linux-bd-zynq7. Can you fix it?

https://github.com/Xilinx/meta-xilinx/tree/master/meta-xilinx-bsp
https://github.com/Xilinx/hdf-examples

**Comment by ckalluri73** [comment]
zybo-zynq7  and zybo-linux-bd-zynq7 are boards that are not actively supported by Xilinx. If you have a working xsa for the two boards, I can push it to the hdf-examples repo.

**Comment by Livius90** [comment]
Your answer is really interesting. Digilent Zybo boards are in the [supported boards in meta-xilinx-bsp](https://github.com/Xilinx/meta-xilinx/blob/rel-v2020.2/meta-xilinx-bsp/README.md). Please fix it because it is supported by Xilinx, All of Digilent target machines are not buildable in Yocto!!

**Comment by Livius90** [comment]
If you do not care about to support Zybo boards, please remove it from your meta layer's [supported boards/machines list](https://github.com/Xilinx/meta-xilinx/blob/rel-v2021.2/meta-xilinx-bsp/README.md#supported-boardsmachines).
